### ISSUE TITLE
Error when running SPIDER_predict, associated with ExperimentHub

### ISSUE THREAD

**Issue by LiuCanidk** [Bin-Chen-Lab/spider#1]
Hi, thanks for developing this nice tool
I was trying this tool on my own dataset but encountered the following error. Hope someone could help
# My code
> SPIDER_predict ( seurat_data = sce,
                 tissue = 'hela',
                 disease = 'cell_line',
                 SPIDER_model_file_path = paste0(prefix, '/SPIDER_python/SPIDER_weight/'), 
                 use_cell_type = 'SingleR',
                 protein = 'All',
                 use_pretrain = 'T', #Using pretrained SPIDER
                 save_path = paste0(prefix, '/SPIDER_results/'), 
                 use_python_path = '/work/home/liucan666/software/mamba/mambaforge/envs/SPIDER/lib/python39.zip', 
                 scarches_path = paste0(prefix, '/scarches-0.4.0/')) 
# My seurat object
> An object of class Seurat 
26271 features across 74253 samples within 1 assay 
Active assay: RNA (26271 features, 2000 variable features)
 3 layers present: counts, data, scale.data
 6 dimensional reductions calculated: pca, umap, harmony, umap_harmony, umap_sct, umap_sct_harmony

# Error report
> Cannot connect to ExperimentHub server, using 'localHub=TRUE' instead
Error in .updateHubDB(hub_bfc, .class, url, proxy, localHub) : 
  Invalid Cache: sqlite file
  Hub has not been added to cache
  Run again with 'localHub=FALSE'
Calls: SPIDER_predict ... ExperimentHub -> .Hub -> .create_cache -> .updateHubDB
In addition: Warning message:
package ‘dplyr’ was built under R version 4.1.3 
Execution halted

How can I fix this, I run this code on a distributed server, which cannot connect to internet when running in computing node, is this problem associated with internet connection?

Thanks in advance

**Comment by Ruoqiao2020** [comment]
It seems that the error you encountered is similar to the error shown in this link: https://support.bioconductor.org/p/9155330/. Probably you'll need to set proxy information to allow ExperimentHub access. Would you try if this works: [Accessing behind a proxy](https://bioconductor.org/packages/release/bioc/vignettes/ExperimentHub/inst/doc/ExperimentHub.html#accessing-behind-a-proxy)

**Comment by LiuCanidk** [comment]
Hi, I fixed it by running hub() in the registering node. It was relevant to the internet proxy in the computing nodes. And running hub() in the normal internet access can help load the cache of the ExperimentHub package.
